# Simulating Coin Flips

In [7]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [8]:
# outcome of one coin flip
np.random.randint(2)

0

In [9]:
#using array to check bounds
np.random.randint(0,3, size=10000).mean()

1.0055000000000001

In [10]:
np.random.randint(4, size=10000).mean()

1.4856

In [12]:
np.random.randint(4,size=25)

array([3, 3, 3, 2, 1, 2, 2, 1, 3, 1, 3, 1, 2, 3, 0, 0, 2, 3, 1, 0, 0, 2, 2,
       2, 3])

In [6]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 1, 1, ..., 1, 1, 0])

In [9]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.49980000000000002

In [10]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [13]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 1, 1, ..., 1, 1, 0])

In [14]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.50870000000000004

In [15]:
np.random.choice([1,2,3,4,5,6], size=50)

array([3, 6, 4, 2, 5, 5, 3, 1, 6, 6, 2, 4, 1, 6, 2, 2, 2, 1, 2, 6, 4, 2, 2,
       6, 1, 6, 4, 2, 5, 4, 5, 5, 5, 4, 5, 3, 2, 2, 2, 1, 1, 6, 3, 4, 6, 1,
       4, 3, 4, 4])

In [17]:
#for array of values like die
np.random.choice([1,2,3,4,5,6],size=1000).mean()

3.5310000000000001

In [16]:
#calculating mean of biased die thrown 50 times
np.random.choice([1,2,3,4,5,6],size=50,p=[0,0.5,0,0.5,0,0]).mean()

2.8399999999999999

In [8]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([1, 0, 0, ..., 0, 0, 0])

In [9]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.193